#!/usr/bin/env python

def masky(array):
    return N.ma.masked_invalid(array, copy=False)

def SnapCompare(dir1, dir2):
    """Simple function to compare two HemeLB snapshots.
    """

    import numpy as N
    from hemeTools.snapSeries import Heme, Diff

    heme1 = Heme(dir1, 0.8/1000.0, snapPattern='*')
    heme2 = Heme(dir2, 0.8/1000.0, snapPattern='*')

    diff = Diff(heme1, heme2)

    """Demand accuracy to 0.01%"""
    accuracy = 1e-4

    for t in diff.times:
        print t

        fields = set((k,v[0]) for k,v in diff[t].dtype.fields.iteritems())
        
        for f in fields:
            name = f[0]
            if name in ['position']:
                continue

            thisVal = diff[t].__getattribute__(name)

            smallerMean = min(N.average(heme1[t].__getattribute__(name)), N.average(heme2[t].__getattribute__(name)))

            if N.max(N.abs(thisVal / smallerMean)) > accuracy:
                print 'At time ' + str(t) + ', field ' + name + ' had a max % difference of ' +  str(N.max(N.abs(thisVal / smallerMean))) + '\n'
                           
if __name__ == '__main__':
    try:
        import argparse
        from os.path import basename, exists

        parser = argparse.ArgumentParser()
        parser.add_argument('input1', help='One input snapshot directory')
        parser.add_argument('input2', help="A second snapshot directory to compare with")
        args = parser.parse_args()
        if not exists(args.input1):
            print "Input file 1 must exist"
            parser.print_help()
            raise SystemExit

        if not exists(args.input2):
            print "Input file 2 must exist"
            parser.print_help()
            raise SystemExit

        SnapCompare(args.input1, args.input2)
    except ImportError:
        import sys
	SnapCompare(sys.argv[1], sys.argv[2])

