#!/usr/bin/env python

def masky(array):
    return N.ma.masked_invalid(array, copy=False)

def SnapCompare(dir1, dir2):
    """Simple function to compare two HemeLB snapshots.
    """

    import numpy as N
    from hemeTools.snapSeries import Heme, Diff

    heme1 = Heme(dir1, 0.8/1000.0, snapPattern='*')
    heme2 = Heme(dir2, 0.8/1000.0, snapPattern='*')

    diff = Diff(heme1, heme2)

    """Demand accuracy to 0.1%"""
    accuracy = 1e-3

    for t in diff.times:
        print t

        fields = set((k,v[0]) for k,v in diff[t].dtype.fields.iteritems())
        
        for f in fields:
            name = f[0]
            if name in ['position', 'id']:
                continue

            thisVal = diff[t].__getattribute__(name)

            smallerElt = N.minimum(heme1[t].__getattribute__(name), heme2[t].__getattribute__(name))

            modded = N.abs(thisVal / smallerElt)

            if N.max(modded) > accuracy:
                worstIndex = N.argmax(modded)
                print 'At time ' + str(t) + ', field ' + name + ' had a max % difference of ' +  str(modded[worstIndex]) \
                  + ' at index (value 1, value 2): ' + str(worstIndex) + ' (' + str(heme1[t].__getattribute__(name)[worstIndex]) \
                  + ', ' + str(heme2[t].__getattribute__(name)[worstIndex]) + ')\n'
                           
if __name__ == '__main__':
    try:
        import argparse
        from os.path import basename, exists

        parser = argparse.ArgumentParser()
        parser.add_argument('input1', help='One input snapshot directory')
        parser.add_argument('input2', help="A second snapshot directory to compare with")
        args = parser.parse_args()
        if not exists(args.input1):
            print "Input file 1 must exist"
            parser.print_help()
            raise SystemExit

        if not exists(args.input2):
            print "Input file 2 must exist"
            parser.print_help()
            raise SystemExit

        SnapCompare(args.input1, args.input2)
    except ImportError:
        import sys
	SnapCompare(sys.argv[1], sys.argv[2])

