#!/bin/bash

SRC="config.cc eVizRLEUtil.c io.cc lb.cc main.cc rt.cc topology.cc"
FLAGS="-O3 -mcpu=itanium2 -no-gcc"
MPI_CC=mpicxx
MPIg_CC=mpicxx
REG_INCLUDE_GRID=-I$HOME/reg_steer_lib/include
REG_LIBS_GRID="-L$HOME/reg_steer_lib/lib64 -L$HOME/libxml2-2.6.30/.libs -lReG_Steer -lReG_Steer_Utils -lReG_Steer_SOAP -lxml2 -lssl" 

function BuildHemeLB_MPIg_Bench {
echo "Building HemeLB with MPIg + benchmarking"
$MPIg_CC \
        -DBENCH \
        $FLAGS $SRC -lm \
        -o hemelb_mpig_bench
}

function BuildHemeLB_MPIg_Vis {
echo "Building HemeLB with MPIg + vis output"
$MPIg_CC \
        -DRG -DFREEROOT \
        $FLAGS $SRC -lm \
        -o hemelb_mpig_vis
}

function BuildHemeLB_MPIg_Vis_Grid_Steering {
echo "Building HemeLB with MPIg + vis output + grid-based ReG steering"
$MPIg_CC \
        -DRG -DFREEROOT -DSTEER \
        $REG_INCLUDE_GRID \
        $REG_LIBS_GRID \
        $FLAGS $SRC -lm \
        -o hemelb_mpig_vis_reg_grid
}

BuildHemeLB_MPIg_Bench
BuildHemeLB_MPIg_Vis
BuildHemeLB_MPIg_Vis_Grid_Steering

