#!/bin/bash

#PBS -N hemelb
#PBS -l nodes=4:ppn=4
#PBS -l walltime=0:20:00
#PBS -o /home/ngs0011/work/hemelb/angio1_16_VIDAR_MPICH.out
#PBS -e /home/ngs0011/work/hemelb/angio1_16_VIDAR_MPICH.err
#PBS -V

. /home/ngs0011/work/RealityGrid/file/reg_steer_lib/reg_steer_configure.sh
export REG_STEER_DIRECTORY=/home/ngs0011/tmp

mpiexec -np 16 /home/ngs0011/work/hemelb/Code/hemelb /home/ngs0011/work/hemelb/Input/angio1_input.asc
