#!/bin/bash --login
#PBS -N $job_name
#PBS -l mppwidth=$cores_reserved
#PBS -l mppnppn=$corespernode
#PBS -l walltime=$wall_time
#PBS -A $budget
#PBS -q $queue
#PBS -m abe
cd $job_results
$run_prefix
rm -rf results
cp $job_config_path/* .
aprun -n $cores -N $coresusedpernode $install_path/bin/hemelb -in config.xml -i $images -s $snapshots -ss $steering