#!/bin/bash --login
#PBS -N $job_name
#PBS -l mppwidth=$cores
#PBS -l mppnppn=$corespernode
#PBS -l walltime=$wall_time
#PBS -A $budget
#PBS -q $queue
#PBS -m abe
cd $job_results
$run_prefix
rm -rf results
aprun -n $cores -N $corespernode $install_path/bin/hemelb -in $regression_test_path/config.xml -out $job_results/results -i 1 -s 1 -ss 1111
$regression_test_path/ImageComparison $regression_test_path/CleanImages results/Images
$regression_test_path/NumericalComparison $regression_test_path/CleanSnapshots results/Snapshots