#!/bin/bash -l

#$$ -S /bin/bash

#$$ -l h_rt=$wall_time

#$$ -l mem=$memory

#$$ -N $job_name

#$$ -pe openmpi $cores_reserved

#$$ -P $project

#$$ -wd $job_results
cd $job_results
$run_prefix
rm -rf results
mpirun -np $cores $install_path/bin/hemelb -in $regression_test_path/config.xml -out $job_results/results -i $images -s $snapshots -ss $steering
$regression_test_path/ImageComparison $regression_test_path/CleanImages results/Images
$regression_test_path/NumericalComparison $regression_test_path/CleanSnapshots results/Snapshots