#!/bin/bash -l

#$$ -S /bin/bash

#$$ -l h_rt=$wall_time

#$$ -l mem=$memory

#$$ -N $job_name

#$$ -pe openmpi $cores_reserved

#$$ -P $project

#$$ -wd $job_results
$node_type_restriction
cd $job_results
$run_prefix
rm -rf results
cp $job_config_path/* .
mpirun -np $cores -machinefile $$TMPDIR/machines $install_path/bin/hemelb -in config.xml -out $job_results/results -i $images -s $snapshots -ss $steering