#!/bin/bash
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores
#$$ -N $job_name
#$$ -e $job_results/${name}.error
#$$ -o $job_results/${name}.output
$run_prefix
rm -rf results
cp $job_config_path/* .
/opt/openmpi/gfortran/1.4.3/bin/mpirun -np $cores $install_path/bin/hemelb -in config.xml -i $images -s $snapshots -ss $steering