#!/bin/bash
#$$ -P $project
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores
#$$ -N $job_name
#$$ -e $job_results/${job_name}.error
#$$ -o $job_results/${job_name}.output
$run_prefix
# This check-scratch-creation code comes from Joerg's example script.
# where are the jobs running:
cat $$PE_HOSTFILE | cut -f 1 -d .  > $job_name.nodes

echo $$JOB_ID > $job_name.jobid

# make sure the local scratch exists
for i in $$(cat $job_name.nodes ); do ssh $$i mkdir -p $job_results ; done
#and run
mpirun -machinefile $$TMPDIR/machines -np $$NSLOTS $install_path/bin/unittests_hemelb -o 'tests.xml'
