#!/bin/bash
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores
#$$ -N $job_name
#$$ -e $job_results/${name}.error
#$$ -o $job_results/${name}.output
$run_prefix
#and run
rm -rf results
/opt/openmpi/gfortran/1.4.3/bin/mpirun -np $cores $install_path/bin/hemelb -in $regression_test_path/config.xml -out $job_results/results -i 1 -s 1 -ss 1111
$regression_test_path/ImageComparison $regression_test_path/CleanImages results/Images
$regression_test_path/NumericalComparison $regression_test_path/CleanSnapshots results/Snapshots