#!/bin/bash
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores
#$$ -N $job_name
#$$ -e $job_results/${job_name}.error
#$$ -o $job_results/${job_name}.output
$run_prefix
#and run
mpirun -np $cores $install_path/bin/unittests_hemelb -o 'tests.xml'
