#!/bin/bash --login
# This file is part of HemeLB and is Copyright (C)
# the HemeLB team and/or their institutions, as detailed in the
# file AUTHORS. This software is provided under the terms of the
# license in the file LICENSE.
#PBS -N $job_name
#PBS -l walltime=$wall_time
#PBS -l cput=$wall_time
#PBS -A $budget
#PBS -q serial
#PBS -m abe
