#!/bin/bash -l
# This file is part of HemeLB and is Copyright (C)
# the HemeLB team and/or their institutions, as detailed in the
# file AUTHORS. This software is provided under the terms of the
# license in the file LICENSE.
#$$ -S /bin/bash

#$$ -l h_rt=$wall_time

#$$ -l mem=$memory

#$$ -N $job_name

#$$ -pe openmpi $cores_reserved

#$$ -P $project

#$$ -wd $job_results
$node_type_restriction
export TMP=$job_results
