#!/bin/bash
# This file is part of HemeLB and is Copyright (C)
# the HemeLB team and/or their institutions, as detailed in the
# file AUTHORS. This software is provided under the terms of the
# license in the file LICENSE.
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores_reserved
#$$ -N $job_name
#$$ -e $job_results/${name}.error
#$$ -o $job_results/${name}.output
