#!/bin/bash
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores_reserved
#$$ -N $job_name
#$$ -e $job_results/${name}.error
#$$ -o $job_results/${name}.output
