#ifndef HEMELB_UNITTESTS_EXTRACTION_EXTRACTION_H
#define HEMELB_UNITTESTS_EXTRACTION_EXTRACTION_H

#include "unittests/extraction/GeometrySelectorTests.h"

#endif /* HEMELB_UNITTESTS_EXTRACTION_EXTRACTION_H */
