#!/usr/bin/env python
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
import pdb
from argparse import ArgumentParser

# Parse command line arguments
parser = ArgumentParser(description='Generate the config file '
                        'described by a profile file')

parser.add_argument('profile', nargs=1, help='The profile to '
                    'use. Other options given override those in the '
                    'profile file.',
                    metavar='PATH')

parser.add_argument('--stl', default=None, dest='StlFile',
                    help='The STL file to use as input',
                    metavar='PATH')
parser.add_argument('--geometry', default=None, dest='OutputGeometryFile',
                    help='Config output file',
                    metavar='PATH')
parser.add_argument('--xml', default=None, dest='OutputXmlFile',
                    help='XML output file',
                    metavar='PATH')
parser.add_argument('--voxel', default=None, type=float, dest='VoxelSizeMetres',
                    help='The voxel size in metres',
                    metavar='FLOAT')

# Parse
args = parser.parse_args()
# Separate the profile argument (argparse puts it in a list)
profile = args.profile[0]
del args.profile

# Import our module late to give erroneous args a chance to be caught
# quickly
from HemeLbSetupTool.Model.Profile import Profile
p = Profile()
p.LoadFromFile(profile)

# override any keys that have been set on cmdline.
p.UpdateAttributesBasedOnCmdLineArgs(vars(args))

p.Generate()
