#!/usr/bin/env python
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
import argparse
p = argparse.ArgumentParser(description='Upgrade an saved profile from "config" to "geometry"')
p.add_argument('input')
p.add_argument('output')
args = p.parse_args()

from HemeLbSetupTool.Util.ProfileUpdateTools import Upgrade
Upgrade(args.input, args.output)
