#!/usr/bin/env python
import pdb
from argparse import ArgumentParser

# Parse command line arguments
parser = ArgumentParser(description='Process an input STL file into'
                        'suitable input for HemeLB.')

parser.add_argument('--profile', default=None, help='Load the profile'
                    'to use from an existing file. Other options given'
                    'override those inthe profile file.')
parser.add_argument('--stl', default=None, dest='StlFile',
                    help='The STL file to use as input')
parser.add_argument('--config', default=None, dest='OutputConfigFile',
                    help='Config output file')
parser.add_argument('--xml', default=None, dest='OutputXmlFile',
                    help='XML output file')

# Parse
args = parser.parse_args()
# Separate the profile argument.
profile = args.profile
del args.profile

# Import our module late to give erroneous args a chance to be caught
# quickly
from HemeLbSetupTool.App import SetupTool
# Pass in the Namespace's __dict__, where it actually stores the
# arguments
app = SetupTool(args=args.__dict__, profile=profile, redirect=False)
app.MainLoop()
