#ifndef HEMELB_FUNCTIONALTESTS_EXAMPLE_EXAMPLE_H
#define HEMELB_FUNCTIONALTESTS_EXAMPLE_EXAMPLE_H

#include "functionaltests/cpptests/example/ExampleTests.h"


#endif /* HEMELB_FUNCTIONALTESTS_EXAMPLE_EXAMPLE_H */
