CXX := mpic++

EXE := hemelb

HEMELB_DBG_LEVEL := 0
HEMELB_STEERING_LIB := basic

HEMELB_CFLAGS :=
HEMELB_CXXFLAGS := -g -pedantic -Wextra -Werror
HEMELB_DEFS := HEMELB_STEERING_LIB=basic
HEMELB_INCLUDEPATHS :=
HEMELB_LIBPATHS :=

