CC=mpicxx
CC=icc
MPIRUN=
EXE=hemelb
DEFS=-DTUFTS_CLUSTER 
FLAGS=-O3 -xT 
INCLUDES=-I/usr/mpi/gcc/mvapich-1.0.1/include
INCLUDE=
LIBS=-pthread -L/usr/mpi/gcc/mvapich-1.0.1/lib -lpmpich++ -lmpich
LIBS=

# to do the final compilation you need something like mpicxx *.o -L /opt/intel/cce/10.1.017/lib -lirc -lcxaguard -limf -lsvml -o exeName
