MPICPUS=4
STEERING_ID=1111

TEST1INPUT=$(HOME)/hemelb/Input/square_duct_32x16x16     500 100 0.01 0 0 $(STEERING_ID)
TEST2INPUT=$(HOME)/hemelb/Input/angio1                   10 200000 0.0001171875 0 0 $(STEERING_ID)
TEST3INPUT=$(HOME)/hemelb/Input/bifurcation_512x512x512  10 200000 0.0001 0 0 $(STEERING_ID)
TEST4INPUT=$(HOME)/hemelb/Input/angio4                   1 2000 0.0009375 0 0  $(STEERING_ID)
TEST5INPUT=$(HOME)/hemelb/Input/angio2                   10 100000 0.000234375 0 0 $(STEERING_ID)
TEST6INPUT=$(HOME)/hemelb/Input/angio8                   10 25000 0.0002245 0 0 $(STEERING_ID)

test1:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST1INPUT)

test2:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST2INPUT)

test3:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST3INPUT)

test4:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST4INPUT)

test5:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST5INPUT)

test6:
	$(MPIRUN) -np $(MPICPUS) ./$(EXE) $(TEST6INPUT)


