CC=icpc

MPIRUN=/home/steven/lammpi/bin/mpirun

EXE=hemelb

DEFS=

FLAGS=-O3 -xT -ipo -pthread -Wunused

INCLUDES=-I/home/steven/lammpi/include

LIBS=-L/home/steven/lammpi/lib -llammpio -llammpi++ -lmpi -llam -ldl

