CC=/usr/local/bin/mpic++

#MPIRUN=/home/steven/lammpi/bin/mpirun

EXE=hemelb

DEFS=-DCCS -DBSD -DDARWIN

FLAGS=-O3 -pthread -Wunused


#INCLUDES=-I/home/steven/lammpi/include
INCLUDES=-I/usr/local/include

#LIBS=-L/home/steven/lammpi/lib -llammpio -llammpi++ -lmpi -llam -ldl
LIBS=-L/usr/local/lib 

