CXX=mpic++

#MPIRUN=/home/steven/lammpi/bin/mpirun

EXE=hemelb

DEFS=-DCCS -DBSD -DDARWIN -DDEBUG

CXXFLAGS=-g  -pthread -Wunused


#INCLUDES=-I/home/steven/lammpi/include
INCLUDES=/usr/local/include

#LIBS=-L/home/steven/lammpi/lib -llammpio -llammpi++ -lmpi -llam -ldl
LIBS=-L/usr/local/lib 

