# -*- mode: makefile; -*-
CXX=/usr/local/bin/mpic++

EXE=hemelb

DEFS=$(addprefix -D, CCS BSD DARWIN DEBUG)

CXXFLAGS=-g  -pthread -Wunused

INCLUDEPATHS=/usr/local/include

LIBPATHS=/usr/local/lib 

# vim: set ft=make :