CC=mpic++.openmpi

#MPIRUN=/home/steven/lammpi/bin/mpirun

EXE=hemelb

DEFS=-DCCS

FLAGS=-O3 -pthread -Wunused

#INCLUDES=-I/home/steven/lammpi/include

#LIBS=-L/home/steven/lammpi/lib -llammpio -llammpi++ -lmpi -llam -ldl

