CC=mpicxx

MPIRUN=/opt/software/mpich2-1.0.3-gcc/bin/mpirun

EXE=hemelb

DEFS=

FLAGS=-O3 -pthread -Wunused -DMPICH_IGNORE_CXX_SEEK

INCLUDES=-I/opt/RealityGrid/git/steer_lib/include/RealityGrid-2.5.0 -I/opt/software/mpich2-1.0.3-gcc/include/

LIBS=-L/opt/RealityGrid/git/steer_lib/lib -lReG_Steer -lReG_Steer_SOAP -lReG_Steer_Utils -lxml2

